// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qawufxqkmpnaaohvashf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhd3VmeHFrbXBuYWFvaHZhc2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mjg3NDUsImV4cCI6MjA2MDQwNDc0NX0.BQN7JYaScJAmHxiMTPI5xdkCVX89E2olvv8YI-PKdD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);